# Generated by Django 6.0.6 on 2026-07-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('Pid', models.IntegerField(primary_key=True, serialize=False)),
                ('Vehicle_type', models.CharField(max_length=20)),
                ('Vehicle_number', models.CharField(max_length=20)),
                ('owner_name', models.CharField(max_length=20)),
                ('parked_hours', models.TimeField()),
                ('paid_amount', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
