# Generated by Django 6.0.6 on 2026-07-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkapp', '0002_parking_delete_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='parked_hours',
            field=models.TextField(max_length=20),
        ),
    ]
